### ISSUE TITLE
Note: vector table relocate potential issue

### ISSUE THREAD

**Issue by scdwyer** [paparazzi/luftboot#7]
In main():

```
/* Set vector table base address. */
SCB_VTOR = APP_ADDRESS & 0xFFFF;
```

This will only work if the bootloader reserved space is less than 0xFFFF, i.e. the app address is less than 0xFFFF. Also note, this utilizes the aliased memory location of the application vector table, but it seems to work just fine using the unaliased address, i.e. just APP_ADDRESS directly. Just a note for future reference in case a bootloader ever gets bigger than 0xFFFF...

**Comment by OpenUAS** [comment]
Added notes to the README.md so it also shows up in repo Wiki
